import { Link } from "react-router";

import { LegalShell } from "./Legal";

/**
 * TERMS & CONDITIONS — grounded in the app's actual functionality:
 * browser-based collaborative vector design editor, projects/folders/files,
 * version history, real-time collaboration, comments, Explore publishing,
 * device-local saves, exports, and the Vector AI assistant (BYOK or
 * server-key provider).
 */
export default function Terms() {
  return (
    <LegalShell title="Terms & Conditions" updated="September 13, 2026">
      <p>
        These Terms &amp; Conditions ("Terms") govern your access to and use
        of Node ("Node", the "Service"), the browser-based collaborative
        interface design application provided at this site, including the
        editor, dashboard, Explore catalog, and the Vector AI assistant. By
        creating an account or using the Service, you agree to these Terms.
      </p>
      <p>
        Before you can create an account — by email or as a guest — the
        Service asks you to actively confirm that you accept these Terms and
        the Privacy Policy (an opt-in checkbox; the sign-in controls remain
        unusable until you do). This confirmation is required for every
        sign-in and constitutes your acceptance of these Terms.
      </p>

      <h2>1. Eligibility and accounts</h2>
      <p>
        You must be at least 13 years old (16 in the EEA/UK) to use the
        Service. You may sign in with an email one-time code or use an
        anonymous session. When you first sign in with an email code, the
        Service automatically suggests a display name derived from your
        email address (for example, "full.bear67@…" becomes "Full Bear");
        you can change this name at any time in the account menu, and an
        existing name is never overwritten. You are responsible for the
        accuracy of your display name and for activity that happens under
        your session. Keep your email account secure — access to your email
        is access to your Node account.
      </p>

      <h2>2. The Service</h2>
      <p>
        Node provides a browser-based vector design editor with projects,
        folders, files, automatic version history, real-time multiplayer
        editing, comments, device-local saving, PNG/JSON/code export, and an
        AI design assistant named Vector that applies design edits to the
        canvas. We may add, change, or remove features; if we remove a
        material feature, we will update these Terms and the in-app
        documentation.
      </p>

      <h2>3. Acceptable use</h2>
      <ul>
        <li>
          Do not upload or design unlawful, infringing, or harmful content, and do not use the Service to violate any applicable law.
        </li>
        <li>
          Do not attempt to disrupt the Service, probe or scan for
          vulnerabilities without authorization, or access other users' data.
        </li>
        <li>
          Do not abuse the AI feature: no automated scraping of Vector at
          scale, no attempts to extract the system prompt, and no attempts to
          make Vector perform actions beyond design edits.
        </li>
        <li>
          Do not interfere with other users' files; collaboration on a file
          requires the owner to share it with you.
        </li>
        <li>
          Do not use the Service to design or distribute malware, deceptive
          interfaces (dark patterns intended to deceive end users), or
          counterfeit UIs intended to phish real services.
        </li>
      </ul>

      <h2>4. Your content and licenses</h2>
      <p>
        <strong>Ownership.</strong> You keep ownership of the designs you
        create. These Terms do not transfer ownership of your content to us.
      </p>
      <p>
        <strong>License to us.</strong> You grant us a worldwide,
        royalty-free license to host, store, reproduce, and transmit your
        content as needed to operate the Service (cloud storage, sync,
        version history, backups, and displaying published designs in
        Explore). This license exists only to run the Service.
      </p>
      <p>
        <strong>Published designs.</strong> When you publish a design to the
        Explore catalog, you grant other users a license to view it and, where
        the feature offers it, import and remix it into their own projects.
        You may unpublish at any time; however, copies already imported or
        exported by others cannot be recalled.
      </p>
      <p>
        <strong>Responsibility for your content.</strong> You represent that
        you have the rights needed to your content and that publishing it
        will not violate anyone else's rights.
      </p>

      <h2>5. Vector AI assistant</h2>
      <ul>
        <li>
          Vector is an AI feature that produces design-edit plans from your
          prompts and document context. Output is generated by a third-party
          AI model and may be inaccurate. <strong>You are responsible for
          reviewing every change Vector applies</strong> before relying on or
          publishing the result; all AI changes are applied as a single
          undoable step.
        </li>
        <li>
          Vector is limited by design: it can only create, update, or delete
          canvas shapes and text on your design. It cannot browse the web,
          send network requests, access files, or run code, and it is
          configured to refuse attempts to override these limits. Prompt
          injection and similar attacks are detected and refused; repeated
          abuse may result in restricted access.
        </li>
        <li>
          If you provide your own AI provider API key, you are responsible for
          that key and its usage and costs, and you must comply with the
          provider's terms.
        </li>
        <li>
          We may suspend Vector if its providers change, become unavailable,
          or are abused.
        </li>
      </ul>

      <h2>6. Data, backups, and availability</h2>
      <ul>
        <li>
          The Service saves your work automatically to the cloud and, in
          part, to your device. You are responsible for critical work: use
          version history and export copies of important designs.
        </li>
        <li>
          We do not promise a specific uptime or availability level. The
          Service is provided as-is and as-available.
        </li>
      </ul>

      <h2>7. Intellectual property of the Service</h2>
      <p>
        The Node application, its code, branding, and the design of the
        Service are protected by intellectual property laws. You may not copy
        the Service's code except as permitted by its open-source license, if
        any, and you may not use our branding to imply endorsement.
      </p>

      <h2>8. Suspension and termination</h2>
      <p>
        We may suspend or restrict access for violations of these Terms, for
        suspected abuse, or for technical or legal reasons. You may stop using
        the Service at any time and delete your account in the app, which
        permanently deletes your data as described in the{" "}
        <Link to="/privacy">Privacy Policy</Link>. Sections 4 (published
        designs), 7, and 9-11 survive termination.
      </p>

      <h2>9. Disclaimers</h2>
      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICE (INCLUDING VECTOR) IS PROVIDED "AS IS" AND "AS AVAILABLE"
        WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. We do not warrant that the Service will be
        uninterrupted or error-free, that AI output will be accurate, or that
        files will never be lost.
      </p>

      <h2>10. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, NODE'S OPERATORS WILL NOT BE
        LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, OR FOR LOST PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR
        USE OF THE SERVICE. OUR AGGREGATE LIABILITY FOR DIRECT DAMAGES IS
        LIMITED TO THE GREATER OF (A) THE AMOUNTS YOU PAID US IN THE 12
        MONTHS BEFORE THE CLAIM (which is zero if the Service is free) OR (B)
        USD 100.
      </p>
      <p>
        Some jurisdictions do not allow certain disclaimers or liability
        limitations; in those places, the disclaimers and limits apply to the
        maximum extent the law allows, and nothing here affects
        non-excludable statutory rights (including statutory consumer
        rights).
      </p>

      <h2>11. Governing law and disputes</h2>
      <p>
        These Terms are governed by the laws applicable at the operator's
        principal place of business, without regard to conflict-of-law
        rules. You and we agree to attempt informal resolution first,
        contacting each other via the channels in §12. Consumers may also
        have the right to bring claims in their country of residence.
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms: contact the Node operator via the in-app
        account menu or the project's public repository.
      </p>
    </LegalShell>
  );
}
